<a href="https://colab.research.google.com/github/edmundzen/dengue-early-warning/blob/main/member4_gemini.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
!pip install -q google-genai python-telegram-bot

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 769.4/769.4 kB 12.8 MB/s eta 0:00:00

**MEMBER 4 : Gemini AI & Integration**

Responsibilities

• Retrieve prioritized dengue alerts from the BigQuery alert_queue table.
• Integrate AI-generated alert content (Recommendations, Executive Summary, and Alert Messages) from the alert_messages table.
• Merge alert data into a unified dataset for processing.
• Develop the Ask Sentinel chatbot to answer officer queries using the Gemini API.
•Implement the Human-in-the-Loop approval workflow, allowing officers to approve or reject alerts before action.
• Store officer decisions in the alert_decisions table for tracking and auditing
• Send approved dengue alerts to officers via Telegram.
• Export processed outputs and chat history as CSV files for reporting and dashboard integration.




## Workflow

Historical Dengue + Weather Data
                │
                ▼
Prediction Model
(Member 1)
                │
                ▼
Risk Scores & Alert Queue
(Member 2)
(BigQuery)
                │
                ▼
Member 4 (Vertex AI Gemini)
                │
      ┌─────────┼─────────┐
      │         │         │
      ▼         ▼         ▼
AI Recommendation
Executive Summary
Alert Message
      │
      ▼
Human-in-the-Loop Approval
(Officer Reviews)
      │
      ├── Rejected → Stop
      │
      ▼
Approved Alert
      │
      ├───────────────┐
      ▼               ▼
Ask Sentinel       Telegram Alert
(Live Q&A)         (Notification)
      │
      ▼
CSV Export + BigQuery Storage

## Step 1: Import Required Libraries

In [6]:
import pandas as pd
import requests
import time

from google import genai
from google.cloud import bigquery
from google.colab import auth, userdata
from datetime import datetime

In [32]:
!gcloud config set project dengue-early-warning

[environment: untagged] Read more to tag: g.co/cloud/project-env-tag.
Updated property [core/project].

In [33]:
!gcloud config list

[component_manager]
disable_update_check = True
[core]
account = shraddhapal1505@gmail.com
project = dengue-early-warning
universe_domain = googleapis.com

Your active configuration is: [default]
[environment: untagged] Read more to tag: g.co/cloud/project-env-tag.

In [38]:
!gcloud services list --enabled --project=dengue-early-warning

NAME                                 TITLE
aiplatform.googleapis.com            Agent Platform API
analyticshub.googleapis.com          Analytics Hub API
apphub.googleapis.com                App Hub API
appoptimize.googleapis.com           App Optimize API
apptopology.googleapis.com           App Topology API
bigquery.googleapis.com              BigQuery API
bigqueryconnection.googleapis.com    BigQuery Connection API
bigquerydatapolicy.googleapis.com    BigQuery Data Policy API
bigquerydatatransfer.googleapis.com  BigQuery Data Transfer API
bigquerymigration.googleapis.com     BigQuery Migration API
bigqueryreservation.googleapis.com   BigQuery Reservation API
bigquerystorage.googleapis.com       BigQuery Storage API
cloudaicompanion.googleapis.com      Gemini for Google Cloud API
cloudapis.googleapis.com             Google Cloud APIs
cloudasset.googleapis.com            Cloud Asset API
cloudtrace.googleapis.com            Cloud Trace API
dataform.googleapis.com              Dataform API
dataplex.googleapis.com              Cloud Dataplex API
datastore.googleapis.com             Cloud Datastore API
designcenter.googleapis.com          Design Center API
geminicloudassist.googleapis.com     Gemini Cloud Assist API
generativelanguage.googleapis.com    Gemini API
logging.googleapis.com               Cloud Logging API
monitoring.googleapis.com            Cloud Monitoring API
recommender.googleapis.com           Recommender API
servicemanagement.googleapis.com     Service Management API
serviceusage.googleapis.com          Service Usage API
sql-component.googleapis.com         Cloud SQL
storage-api.googleapis.com           Google Cloud Storage JSON API
storage-component.googleapis.com     Cloud Storage
storage.googleapis.com               Cloud Storage API
telemetry.googleapis.com             Telemetry API

In [7]:
from google import genai
from google.genai import types

## Step 2: Authenticate with Google Cloud

In [8]:
auth.authenticate_user()

import subprocess
acct = subprocess.run(["gcloud","config","get-value","account"],
                      capture_output=True, text=True).stdout.strip()
print("Signed in as:", acct)

Signed in as: shraddhapal1505@gmail.com

In [28]:

PROJECT_ID = "dengue-early-warning"
LOCATION = "global"

from google import genai

client = genai.Client(
    vertexai=True,
    project=PROJECT_ID,
    location=LOCATION
)

## Step 3: Connect to BigQuery

In [2]:
from google.cloud import bigquery

PROJECT_ID = "dengue-early-warning"

bq_client = bigquery.Client(project=PROJECT_ID)

print("BigQuery Connected!")

BigQuery Connected!

In [10]:
query = """
SELECT *
FROM `dengue-early-warning.dengue_ew.alert_queue`
ORDER BY risk_score DESC
"""
inspection_df = bq_client.query(query).to_dataframe()

In [12]:
#rename
inspection_df.rename(columns={
    "executive_summary": "Executive_Summary",
    "recommendation": "AI_Recommendation"
}, inplace=True)

In [13]:
print("Columns in alert_queue:")

print(inspection_df.columns.tolist())

Columns in alert_queue:
['alert_id', 'cell_id', 'lat', 'lon', 'risk_score', 'risk_level', 'forecast_value', 'case_density_14d', 'recurrence', 'rank', 'created_at', 'alert_message', 'Executive_Summary', 'AI_Recommendation']

In [14]:
inspection_df[[
    "cell_id",
    "risk_level",
    "risk_score"
]].head()

             cell_id risk_level  risk_score
0   1.33425_103.8825   Critical       38.61
1  1.34775_103.95225   Critical       34.49
2     1.314_103.9275       High       24.20
3    1.314_103.85325       High       23.00
4    1.3815_103.9365       High       21.72

In [15]:
PROJECT_ID = "dengue-early-warning"

bq_client = bigquery.Client(project=PROJECT_ID)

In [16]:
inspection_df.head()

,alert_id,cell_id,lat,lon,risk_score,risk_level,forecast_value,case_density_14d,recurrence,rank,created_at,alert_message,Executive_Summary,AI_Recommendation
0,fe2710b8-0122-4528-9179-0f395c16c0d3,1.33425_103.8825,1.33425,103.88250,38.61,Critical,4.081365,86.0,0.100819,1,2026-07-23 13:36:56.166241+00:00,Severity: CRITICAL\nReason: Highest 14-day cas...,Cell 1.33425_103.8825 is the top-ranked dengue...,1) Dispatch officers within 24h for door-to-do...
1,85dbe860-a710-4a34-a386-11191f50cf1d,1.34775_103.95225,1.34775,103.95225,34.49,Critical,3.601444,76.0,0.063460,2,2026-07-23 13:36:56.166241+00:00,Severity: CRITICAL\nReason: Second-highest clu...,Cell 1.34775_103.95225 carries a critical scor...,1) Schedule inspection within 48h. 2) Clear st...
2,8a93a1da-b59f-4f63-bdfa-be371f658b55,1.314_103.9275,1.31400,103.92750,24.20,High,2.419172,51.0,0.075230,3,2026-07-23 13:36:56.166241+00:00,Severity: HIGH\nReason: Elevated case density ...,Cell 1.314_103.9275 is a high-risk emerging ho...,1) Add to this week inspection route. 2) Remov...
3,ae78f537-b055-4250-931a-9bf1e7004ad0,1.314_103.85325,1.31400,103.85325,23.00,High,2.275486,48.0,0.315763,4,2026-07-23 13:36:56.166241+00:00,Severity: HIGH\nReason: 48 cases with a 2.3 fo...,Cell 1.314_103.85325 scores 23.0 and stands ou...,1) Inspect and trace the recurring source. 2) ...
4,37834b62-90bb-4bf1-ad18-2ae087c1ccf1,1.3815_103.9365,1.38150,103.93650,21.72,High,2.133953,45.0,0.026612,5,2026-07-23 13:36:56.166241+00:00,"Severity: HIGH\nReason: 45 cases, forecast 2.1...",Cell 1.3815_103.9365 (score 21.7) shows steady...,1) Include in weekly inspection. 2) Clear stag...

In [17]:
print(inspection_df["risk_score"].tolist())

[38.61, 34.49, 24.2, 23.0, 21.72, 21.31, 20.07]

## Step 5: Generate AI Recommendation (Vertex AI Gemini)

In [18]:
from google import genai

gemini_client = genai.Client(
    vertexai=True,
    project=PROJECT_ID,
    location="global"
)

print("Vertex AI Connected!")

Vertex AI Connected!

In [41]:
response = gemini_client.models.generate_content(
    model="gemini-2.5-flash",
    contents="Say Hello"
)

print(response.text)

Hello! How can I help you today?

In [44]:
def generate_recommendation(row):

    prompt = f"""
You are a Public Health Officer.

Analyze this dengue alert.

Cell ID: {row['cell_id']}
Risk Score: {row['risk_score']}
Risk Level: {row['risk_level']}

Provide your answer in exactly this format:

Risk Summary:
(2 short lines)

Inspection Priority:
(One sentence)

Recommended Actions:
• Action 1
• Action 2
• Action 3

Expected Impact:
(One short sentence)

Keep the response under 150 words.
"""

    try:

        response = gemini_client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt
        )

        return response.text

    except Exception as e:

        return f"Error: {e}"

In [45]:
inspection_df[[
    "cell_id",
    "risk_level",
    "risk_score",
    "AI_Recommendation"
]].head()

,cell_id,risk_level,risk_score,AI_Recommendation
0,1.33425_103.8825,Critical,38.61,Risk Summary:\nThe location at Cell ID 1.33425...
1,1.34775_103.95225,Critical,34.49,Risk Summary:\nCell 1.34775_103.95225 is curre...
2,1.314_103.9275,High,24.20,Risk Summary:\nCell 1.314_103.9275 is at a hig...
3,1.314_103.85325,High,23.00,Risk Summary:\nHigh dengue transmission risk i...
4,1.3815_103.9365,High,21.72,Risk Summary:\nA high dengue risk (score 21.72...

## Step 6: Generate Executive Summary

In [24]:
import time

def executive_summary(row):

    prompt = f"""
You are a dengue surveillance analyst.

Summarize this alert in less than 70 words.

Cell ID: {row['cell_id']}
Risk Level: {row['risk_level']}
Risk Score: {row['risk_score']}
Forecast Value: {row['forecast_value']}
Case Density: {row['case_density_14d']}
Recurrence: {row['recurrence']}
"""

    for attempt in range(3):

        try:

            response = gemini_client.models.generate_content(
                model="gemini-2.5-flash",
                contents=prompt
            )

            return response.text

        except Exception:

            time.sleep(5)

    return "Executive Summary unavailable."
    return "Executive summary unavailable."

In [ ]:
print(inspection_df.columns.tolist())

['alert_id', 'cell_id', 'lat', 'lon', 'risk_score', 'risk_level', 'forecast_value', 'case_density_14d', 'recurrence', 'rank', 'created_at', 'AI_Recommendation']

In [ ]:
inspection_df[[
    "cell_id",
    "Executive_Summary"
]].head()

             cell_id                                  Executive_Summary
0   1.33425_103.8825  Cell 1.33425_103.8825 is the top-ranked dengue...
1  1.34775_103.95225  Cell 1.34775_103.95225 carries a critical scor...
2     1.314_103.9275  Cell 1.314_103.9275 is a high-risk emerging ho...
3    1.314_103.85325  Cell 1.314_103.85325 scores 23.0 and stands ou...
4    1.3815_103.9365  Cell 1.3815_103.9365 (score 21.7) shows steady...

## Step 7: Generate Severity Live Alert Messages

Purpose:
Generate severity-based live alert messages for officers.

In [23]:
inspection_df["AI_Recommendation"] = inspection_df.apply(
    generate_recommendation,
    axis=1
)

In [25]:
inspection_df["Executive_Summary"] = inspection_df.apply(
    executive_summary,
    axis=1
)

In [60]:
inspection_df["alert_message"] = inspection_df.apply(
    generate_alert,
    axis=1
)

In [46]:
def generate_alert(row):

    prompt = f"""
You are the Officer of the Day.

Generate a professional dengue alert.

Cell ID: {row['cell_id']}
Risk Level: {row['risk_level']}
Risk Score: {row['risk_score']}

Write:

Alert Level:
Reason:
Immediate Action:

Keep it under 80 words.
"""

    try:

        response = gemini_client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt
        )

        return response.text

    except Exception as e:

        return f"Error: {e}"

In [47]:
inspection_df[["cell_id","risk_level","alert_message"]].head()

,cell_id,risk_level,alert_message
0,1.33425_103.8825,Critical,**Alert Level:** CRITICAL\n\n**Reason:** Cell ...
1,1.34775_103.95225,Critical,**Alert Level:** CRITICAL (Risk Score: 34.49)\...
2,1.314_103.9275,High,**Alert Level:** High (Sector 1.314_103.9275)\...
3,1.314_103.85325,High,**Alert Level:** HIGH (Cell ID: 1.314_103.8532...
4,1.3815_103.9365,High,**Alert Level:** HIGH — Cell ID: 1.3815_103.93...

## Step 8: Human-in-the-Loop Approval

Purpose:
Every AI-generated alert is reviewed by the Officer of the Day before execution.
Only approved alerts proceed to notification.

In [48]:
from datetime import datetime

def officer_decision(row, decision, officer, reason):

    return {
        "alert_id": row["alert_id"],
        "cell_id": row["cell_id"],
        "decision": decision,
        "officer": officer,
        "reason": reason,
        "decided_at": datetime.now()
    }


## Step 9: Officer Approval Workflow

In [49]:
decision_list = []

for _, row in inspection_df.iterrows():

    if row["risk_score"] >= 30:

        decision = "Approved"
        reason = "Critical dengue risk"

    elif row["risk_score"] >= 20:

        decision = "Approved"
        reason = "High dengue risk"

    else:

        decision = "Rejected"
        reason = "Risk below threshold"

    decision_list.append(

        officer_decision(
            row,
            decision,
            "Health Officer",
            reason
        )
    )

decision_df = pd.DataFrame(decision_list)

decision_df.head()

,alert_id,cell_id,decision,officer,reason,decided_at
0,fe2710b8-0122-4528-9179-0f395c16c0d3,1.33425_103.8825,Approved,Health Officer,Critical dengue risk,2026-07-27 16:34:46.219402
1,85dbe860-a710-4a34-a386-11191f50cf1d,1.34775_103.95225,Approved,Health Officer,Critical dengue risk,2026-07-27 16:34:46.219512
2,8a93a1da-b59f-4f63-bdfa-be371f658b55,1.314_103.9275,Approved,Health Officer,High dengue risk,2026-07-27 16:34:46.219590
3,ae78f537-b055-4250-931a-9bf1e7004ad0,1.314_103.85325,Approved,Health Officer,High dengue risk,2026-07-27 16:34:46.219658
4,37834b62-90bb-4bf1-ad18-2ae087c1ccf1,1.3815_103.9365,Approved,Health Officer,High dengue risk,2026-07-27 16:34:46.219732

## Step 10: Ask Sentinel Chatbot

Purpose:
Allow officers to ask questions about a dengue alert and receive grounded AI explanations.

In [50]:
def ask_sentinel(row, question):

    prompt = f"""
You are Sentinel AI.

You assist dengue surveillance officers.

Current Alert

Alert ID: {row['alert_id']}
Cell ID: {row['cell_id']}
Risk Level: {row['risk_level']}
Risk Score: {row['risk_score']}
Forecast Value: {row['forecast_value']}
Case Density: {row['case_density_14d']}
Recurrence: {row['recurrence']}

Officer Question:
{question}

Answer using this format:

Risk Summary:
Inspection Priority:
Recommended Actions:
Expected Impact:

Keep the answer under 150 words.
"""

    try:

        response = gemini_client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt
        )

        return response.text

    except Exception as e:

        return f"Error: {e}"

In [51]:
#test chatbot
question = "Why is this area high risk?"

answer = ask_sentinel(
    inspection_df.iloc[0],
    question
)

print(answer)

Risk Summary: The critical risk level is primarily driven by an exceptionally high current case density (86.0), indicating significant active transmission. The forecast value (4.08) suggests a high likelihood of new cases or an impending outbreak.

Inspection Priority: Immediate. This cell demands urgent attention due to its critical risk status and the high number of existing cases.

Recommended Actions: Conduct rapid premise-to-premise inspections, targeted vector control operations (larviciding, fogging), and immediate community engagement for source reduction.

Expected Impact: Rapidly mitigate ongoing transmission, reduce the local vector population, and prevent further dengue infections within the community.

In [53]:
question = input("Ask Sentinel: ")

answer = ask_sentinel(
    inspection_df.iloc[0],
    question
)

print(answer)

Ask Sentinel: Why did this cell receive a Critical risk level?
Risk Summary:
This cell is classified as Critical due to a high Risk Score of 38.61, driven by an exceptionally high Case Density of 86.0 and a significant Forecast Value of 4.08, indicating a strong likelihood of imminent case increase.

Inspection Priority:
Immediate - Highest Priority.

Recommended Actions:
Conduct urgent field inspection to identify and eliminate breeding sites. Implement aggressive source reduction and enhanced larval surveillance. Consider targeted public awareness campaigns.

Expected Impact:
Prompt intervention will mitigate the risk of an impending outbreak, reduce local transmission, and protect the community from further dengue spread.

## Step 11: Telegram Notification

Purpose:
Send approved dengue alerts to field officers through Telegram.

In [55]:
import requests

BOT_TOKEN = userdata.get("BOT_TOKEN")
CHAT_ID = userdata.get("CHAT_ID")

In [56]:
def send_telegram_alert(row):

    message = f"""
🚨 DENGUE EARLY WARNING

Cell ID: {row['cell_id']}

Risk Level: {row['risk_level']}

Risk Score: {row['risk_score']}

Executive Summary

{row['Executive_Summary']}

AI Recommendation

{row['AI_Recommendation']}
"""

    url = f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage"

    payload = {

        "chat_id": CHAT_ID,

        "text": message
    }

    requests.post(
        url,
        json=payload
    )

In [57]:
#send approval message
for _, row in inspection_df.iterrows():

    if row["risk_score"] >= 20:

        send_telegram_alert(row)

print("✅ Telegram alerts sent.")

✅ Telegram alerts sent.

## Step 12: Export Results to CSV

Purpose:
Save AI-generated outputs and officer decisions for reporting and dashboard integration.

In [58]:
# Save AI recommendations, summaries, and alerts
inspection_df.to_csv("AI_Recommendation.csv", index=False)

# Save officer decisions
decision_df.to_csv("alert_decisions.csv", index=False)

print("✅ CSV files exported successfully.")

✅ CSV files exported successfully.

## Step 13: Save Sentinel Chat History

Purpose:
Store officer questions and Sentinel AI responses for auditing and future analysis.

In [59]:
chat_history = []

questions = [
    "Why is this area high risk?",
    "What actions should officers take?",
    "Should this alert be approved?"
]

for q in questions:

    ans = ask_sentinel(
        inspection_df.iloc[0],
        q
    )

    chat_history.append({

        "alert_id": inspection_df.iloc[0]["alert_id"],

        "question": q,

        "answer": ans

    })

chat_df = pd.DataFrame(chat_history)

chat_df.to_csv("sentinel_chat_history.csv", index=False)

print("✅ Chat history saved.")

✅ Chat history saved.

## Step 14: Upload Officer Decisions to BigQuery

Purpose:
Store officer approval decisions in BigQuery for dashboard visualization and tracking.

In [61]:
job = bq_client.load_table_from_dataframe(

    decision_df,

    "dengue-early-warning.dengue_ew.alert_decisions",

    job_config=bigquery.LoadJobConfig(

        write_disposition="WRITE_TRUNCATE"

    )

)

job.result()

print("✅ alert_decisions uploaded to BigQuery.")

✅ alert_decisions uploaded to BigQuery.

## Step 15: Final Outputs

Purpose:
Preview the generated outputs before deployment.

In [62]:
print("Inspection Data")

inspection_df.head()

Inspection Data

,alert_id,cell_id,lat,lon,risk_score,risk_level,forecast_value,case_density_14d,recurrence,rank,created_at,alert_message,Executive_Summary,AI_Recommendation
0,fe2710b8-0122-4528-9179-0f395c16c0d3,1.33425_103.8825,1.33425,103.88250,38.61,Critical,4.081365,86.0,0.100819,1,2026-07-23 13:36:56.166241+00:00,**Alert Level:** CRITICAL\n**Reason:** Elevate...,Dengue alert for Cell ID 1.33425_103.8825 is a...,Risk Summary:\nThe location at Cell ID 1.33425...
1,85dbe860-a710-4a34-a386-11191f50cf1d,1.34775_103.95225,1.34775,103.95225,34.49,Critical,3.601444,76.0,0.063460,2,2026-07-23 13:36:56.166241+00:00,**Alert Level:** CRITICAL\n**Reason:** Sustain...,Cell 1.34775_103.95225 is at a **Critical** de...,Risk Summary:\nCell 1.34775_103.95225 is curre...
2,8a93a1da-b59f-4f63-bdfa-be371f658b55,1.314_103.9275,1.31400,103.92750,24.20,High,2.419172,51.0,0.075230,3,2026-07-23 13:36:56.166241+00:00,Alert Level: High Dengue Alert\nReason: Elevat...,Cell ID 1.314_103.9275 shows a **High** dengue...,Risk Summary:\nCell 1.314_103.9275 is at a hig...
3,ae78f537-b055-4250-931a-9bf1e7004ad0,1.314_103.85325,1.31400,103.85325,23.00,High,2.275486,48.0,0.315763,4,2026-07-23 13:36:56.166241+00:00,Alert Level: HIGH\nReason: Cell ID 1.314_103.8...,Dengue alert for Cell ID 1.314_103.85325 indic...,Risk Summary:\nHigh dengue transmission risk i...
4,37834b62-90bb-4bf1-ad18-2ae087c1ccf1,1.3815_103.9365,1.38150,103.93650,21.72,High,2.133953,45.0,0.026612,5,2026-07-23 13:36:56.166241+00:00,**Alert Level:** High Dengue Risk\n**Reason:**...,Cell ID 1.3815_103.9365 shows a High Dengue Ri...,Risk Summary:\nA high dengue risk (score 21.72...

In [63]:
print("Officer Decisions")

decision_df.head()

Officer Decisions

,alert_id,cell_id,decision,officer,reason,decided_at
0,fe2710b8-0122-4528-9179-0f395c16c0d3,1.33425_103.8825,Approved,Health Officer,Critical dengue risk,2026-07-27 16:34:46.219402
1,85dbe860-a710-4a34-a386-11191f50cf1d,1.34775_103.95225,Approved,Health Officer,Critical dengue risk,2026-07-27 16:34:46.219512
2,8a93a1da-b59f-4f63-bdfa-be371f658b55,1.314_103.9275,Approved,Health Officer,High dengue risk,2026-07-27 16:34:46.219590
3,ae78f537-b055-4250-931a-9bf1e7004ad0,1.314_103.85325,Approved,Health Officer,High dengue risk,2026-07-27 16:34:46.219658
4,37834b62-90bb-4bf1-ad18-2ae087c1ccf1,1.3815_103.9365,Approved,Health Officer,High dengue risk,2026-07-27 16:34:46.219732

In [64]:
print("Sentinel Chat History")

chat_df.head()

Sentinel Chat History

,alert_id,question,answer
0,fe2710b8-0122-4528-9179-0f395c16c0d3,Why is this area high risk?,**Risk Summary:** This area (Cell ID: 1.33425_...
1,fe2710b8-0122-4528-9179-0f395c16c0d3,What actions should officers take?,Risk Summary: This cell (1.33425_103.8825) exh...
2,fe2710b8-0122-4528-9179-0f395c16c0d3,Should this alert be approved?,**Risk Summary:**\nThis alert indicates a **Cr...

##Conclusion

Sentinel AI successfully completed the following workflow:

1. Retrieved prioritized dengue alerts from BigQuery.
2. Generated AI Recommendations using Gemini.
3. Created Executive Summaries for health officers.
4. Generated Severity Alert Messages.
5. Supported Grounded Q&A through the Ask Sentinel chatbot.
6. Enabled Human-in-the-Loop approval decisions.
7. Sent approved alerts via Telegram.
8. Exported reports to CSV.
9. Uploaded officer decisions to BigQuery.

The system provides an end-to-end AI-assisted dengue early warning workflow for public health surveillance.